export const SET_HTMLEDITOR_CONTENT = 'SET_HTMLEDITOR_CONTENT'
export const SET_CSSEDITOR_CONTENT = 'SET_CSSEDITOR_CONTENT'
export const SET_JSEDITOR_CONTENT = 'SET_JSEDITOR_CONTENT'
export const SET_RESULT_CONTENT = 'SET_RESULT_CONTENT'